spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookstore

server:
  port: 8082

jwt:
  #Generate secret using command 'openssl rand -base64 64' via git bash. Need this to avoid WeakKeyException error
  secret: DXAFhX1IzlUc4dTik1tolHqytIkA4A8R4Vv0RtRS0Ig53eB4vhrWmco6YUkLg14iVVHPDwX/TrujItFjWCtAUg== # secret key
  expiration: 3600000 # Token validity in milliseconds

logging:
  level:
    org:
      springframework:
        data: DEBUG